version: '3.3'

services:
  mysql:
    container_name: keycloak-mysql
    image: mysql/mysql-server:8.0
    volumes:
      - C:\Users\oskri\OneDrive\Documentos\sql\keycloak:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MySQL_ALLOW_EMPTY_PASSWORD: yes
    networks:
      - keycloak-mysql
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: ecommerce
      DB_USER: admin
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    networks:
      - keycloak-mysql
      - spring-keycloak
    restart: on-failure
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
  db:
    image: mysql/mysql-server:8.0
    container_name: spring-mysql
    restart: always
    ports:
      - '3306:3306'
    networks:
      - springmysql-net
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - C:\Users\oskri\OneDrive\Documentos\sql\spring:/var/lib/mysql
  app:
    image: sleepypoem:ecommerce-0.4
    build:
      context: .
    container_name: spring-app
    depends_on:
      - db
      - keycloak
    ports:
      - "8081:8081"
    networks:
      - springmysql-net
      - spring-keycloak
    environment:
      - MYSQL_HOST=db
      - MYSQL_USERNAME=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=ecommerce
      - MYSQL_PORT=3306
      - LOCAL_HOST=host.docker.internal
    links:
      - keycloak
    extra_hosts:
      - "host.docker.internal:host-gateway"
  app-front:
    image: sleepypoem:ecommerce-front-0.4
    container_name: spring-app-front
    build:
        context: ./front
        dockerfile: Dockerfile-front
    ports:
        - "4200:4200"
        - "3000:3000"
        - "8083:8080"
networks:
  springmysql-net:
  spring-keycloak:
  keycloak-mysql:
    driver: bridge