spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:ecommerce}
    username: ${MYSQL_USERNAME:admin}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth-server.prefix}${auth-server.realm-name}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

auth-server:
  realm-name: Final-project
  prefix: http://localhost:8080/auth/realms/
  admin-rest-prefix: http://localhost:8080/auth/admin/realms/
  token-endpoint: ${auth-server.prefix}${auth-server.realm-name}/protocol/openid-connect/token
server:
  port: 8081
  servlet:
    contextPath: /api

management:
  endpoints:
    web:
      exposure.include: health, metrics, loggers
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      springframework:
        security: DEBUG
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE