FROM node:17-alpine AS builder
### STAGE 1: Build ###
LABEL authors="sleepypoem"
WORKDIR /ecommerce-front
COPY /ecommerce-front/package.json .
RUN npm install
COPY ./ecommerce-front .
RUN npm run build

### STAGE 2: Run ###
FROM nginx:1.21.3
WORKDIR /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
RUN rm -rf ./*
COPY --from=builder /ecommerce-front/build .

ENTRYPOINT ["nginx", "-g", "daemon off;"]